// Course categories grouped by duration
export const courseCategories = {
	Long: [
		"3D Animation",
		"VFX",
		"Game Design",
		"Game Development",
		"Interior/ Exterior",
	],
	Mid: [
		"Graphics Design",
		"3D Animation",
		"VFX",
		"Graphic Web Design and Development",
		"Motion Graphics Design",
		"UI/UX",
		"Video / Audio",
	],
	Short: [
		"Graphics Design",
		"2D Animation",
		"3D Animation",
		"VFX",
		"Graphic Web Design and Development",
		"Motion Graphics Design",
		"Game Design",
		"Video / Audio",
		"AI",
		"Interior/ Exterior",
	],
};

// Course class definition
class Course {
	constructor(
		courseCode,
		courseFamily,
		name,
		duration,
		months,
		categories,
		totalFees,
		lumpSum,
		terms,
		brouchureLink = "",
		degree = false
	) {
		this.courseCode = courseCode;
		this.courseFamily = courseFamily;
		this.name = name;
		this.duration = duration;
		this.months = months;
		this.categories = categories; // Changed to accept multiple categories
		this.totalFees = totalFees;
		this.registrationFees = 5900; // Fixed registration fee
		this.downPayment = degree ? 80000 : 30000; // Fixed down payment
		this.lumpSum = lumpSum;
		this.terms = terms;
		this.degree = degree;
		this.brouchureLink = brouchureLink;
	}

	get totalSubmission() {
		return this.totalFees - this.downPayment;
	}

	get totalNoOfQuarterlyInstallments() {
		if (this.degree) {
			return this.months / 6 - 1;
		} else {
			return Math.floor((this.months - 1) / 3);
		}
	}

	get installments() {
		if (this.degree) {
			return this.totalSubmission / 5;
		} else {
			return this.totalSubmission / Math.floor((this.months - 1) / 3);
		}
	}

	get monthlyInstallments_1() {
		return Math.round(this.totalSubmission / (this.months - 1));
	}

	get monthlyInstallments_2() {
		return Math.round(this.totalSubmission / (this.months - 2));
	}

	get monthlyInstallments_3() {
		return Math.round(this.totalSubmission / (this.months - 3));
	}

	get monthlyInstallments_4() {
		return Math.round(this.totalSubmission / (this.months - 4));
	}
}

// Course details
export const courses = [
	new Course(
		"3168-AAIPP-A3DD",
		"AAIPP Animation - 3168",
		"AAIPP-Advanced 3D Design",
		"Long",
		22,
		["3D Animation"],
		253508,
		229436,
		[
			[
				"Adobe Illustrator CC",
				"Adobe Photoshop CC",
				"Storyboarder",
				"Adobe Premier Pro CC",
				"Adobe Audition CC",
				"Adobe Animate CC",
				"Adobe After Effects CC",
				"Gen Ai tools for Text/Image/Video",
				"Term-end Portfolio",
			],
			[
				"Autodesk Maya",
				"Maxon Zbrush",
				"Adobe Substance Painter",
				"Reality Capture",
				"Arnold",
				"Gen Ai tools for 3D Assets Creation & Animation",
				"Term-end Portfolio",
			],
			[],
			[],
			[],
			[],
		],
		`https://drive.google.com/file/d/1Cc0kLLDKXwaNtS9tKuPM9GGDGJbkTJdl/view?usp=sharing`
	),

	new Course(
		"3168-AAIPP-APAUE",
		"AAIPP Animation - 3168",
		"AAIPP-Advanced Program in Animation with Unreal Engine",
		"Long",
		27,
		["3D Animation", "Game Design"],
		317936,
		278170,
		[
			[
				"Adobe Illustrator CC",
				"Adobe Photoshop CC",
				"Storyboarder",
				"Adobe Premier Pro CC",
				"Adobe Audition CC",
				"Adobe Animate CC",
				"Adobe After Effects CC",
				"Gen Ai tools for Text/Image/Video",
				"Term-end Portfolio",
			],
			[
				"Autodesk Maya",
				"Maxon Zbrush",
				"Adobe Substance Painter",
				"Reality Capture",
				"Arnold",
				"Gen Ai tools for 3D Assets Creation & Animation",
				"Term-end Portfolio",
			],
			[
				"Autodesk Maya nCloth & X-Gen",
				"Unreal Engine",
				"Meta Human",
				"Term-end Portfolio",
				"LinkedIn",
				"Upwork",
			],
			[],
			[],
			[],
		],
		`https://drive.google.com/file/d/1m8LgHwjB53BW8YkHWf6k6Mr5U97mTe4N/view?usp=sharing`
	),
	new Course(
		"3168-AAIPP-DV",
		"AAIPP Animation - 3168",
		"AAIPP-Design and Visualization",
		"Mid",
		11,
		["Graphics Design", "Video / Audio"],
		110616,
		106250,
		[
			[
				"Adobe Illustrator CC",
				"Adobe Photoshop CC",
				"Storyboarder",
				"Adobe Premier Pro CC",
				"Adobe Audition CC",
				"Adobe Animate CC",
				"Adobe After Effects CC",
				"Gen Ai tools for Text/Image/Video",
				"Term-end Portfolio",
			],
			[],
			[],
			[],
			[],
			[],
		],
	),
	new Course(
		"3171-AAIPP-A3DV",
		"AAIPP APAVID - 3171",
		"AAIPP-Advanced 3D Visualization",
		"Mid",
		18,
		["3D Animation"],
		213388,
		196278,
		[
			[
				"Adobe Illustrator CC",
				"Storyboarder",
				"Adobe Premiere Pro",
				"Adobe Audition CC",
				"Adobe Animate CC",
				"Adobe After Effects CC",
				"Gen Ai Tools",
			],
			[
				"AutoCAD",
				"3ds Max",
				"V-Ray",
				"Adobe Substance Painter",
				"SketchUp",
				"Gen Ai Tools",
			],
			[],
			[],
			[],
			[],
		],
		`https://drive.google.com/file/d/1vFsE4Tu_01_5baZLA9yMJ3l4Rn0MoVnN/view?usp=sharing`
	),
	new Course(
		"3171-AAIPP-APAVID",
		"AAIPP APAVID - 3171",
		"AAIPP-Advanced Program in Architectural Visualization and Interior Design",
		"Long",
		27,
		["Interior/ Exterior"],
		320532,
		280294,
		[
			[
				"Adobe Illustrator CC",
				"Storyboarder",
				"Adobe Premiere Pro",
				"Adobe Audition CC",
				"Adobe Animate CC",
				"Adobe After Effects CC",
				"Gen Ai Tools",
			],
			[
				"AutoCAD",
				"3ds Max",
				"V-Ray",
				"Adobe Substance Painter",
				"SketchUp",
				"Gen Ai Tools",
			],
			[
				"Blender",
				"Unreal Engine",
				"Twinmotion",
				"Term-end Portfolio",
				"LinkedIn",
				"Upwork",
			],
			[],
			[],
			[],
		],
		`https://drive.google.com/file/d/1pZIcvJOCV3iWD-ebK1aceMS_rnaKmiBz/view?usp=sharing`
	),
	new Course(
		"3170-AAIPP-BD",
		"AAIPP Broadcast - 3170",
		"AAIPP-Broadcast Design",
		"Long",
		19,
		["3D Animation"],
		227430,
		208078,
		[
			[
				"Adobe Illustrator CC",
				"Adobe Photoshop CC",
				"Storyboarder",
				"Adobe Premier Pro CC",
				"Adobe Audition CC",
				"Adobe Animate CC",
				"Adobe After Effects CC",
				"Gen Ai tools for Text/Image/Video",
				"Term-end Portfolio",
			],
			[
				"AutoCAD",
				"3ds Max",
				"V-Ray",
				"Adobe Substance Painter",
				"SketchUp",
				"Gen Ai Tools",
			],
			[],
			[],
			[],
			[],
		],
		`https://drive.google.com/file/d/1V-RGujeZDapZMo4FPN39y40K8IrCLQdD/view?usp=sharing`
	),
	new Course(
		"3169-AAIPP-A3DD",
		"AAIPP VFX - 3169",
		"AAIPP-Advanced 3D Design for VFX",
		"Long",
		20,
		["VFX"],
		235808,
		214686,
		[
			[
				"Adobe Illustrator CC",
				"Adobe Photoshop CC",
				"Storyboarder",
				"Adobe Premier Pro CC",
				"Adobe Audition CC",
				"Adobe Animate CC",
				"Adobe After Effects CC",
				"Gen Ai tools for Text/Image/Video",
				"Term-end Portfolio",
			],
			[
				"Autodesk Maya",
				"Adobe Substance Painter",
				"Reality Capture",
				"Arnold",
				"Gen Ai tools for 3D Assets Creation & Animation",
				"Term-end Portfolio",
			],
			[],
			[],
			[],
			[],
		],
		`https://drive.google.com/file/d/19KG_T2crxvFh138y4qQo2adK4Ehnn9Mn/view?usp=sharing`
	),
	new Course(
		"3169-AAIPP-AdvVE",
		"AAIPP VFX - 3169",
		"AAIPP-Advanced Program in Visual Effects",
		"Long",
		29,
		["VFX"],
		334338,
		290796,
		[
			[
				"Adobe Illustrator CC",
				"Adobe Photoshop CC",
				"Storyboarder",
				"Adobe Premier Pro CC",
				"Adobe Audition CC",
				"Adobe Animate CC",
				"Adobe After Effects CC",
				"Gen Ai tools for Text/Image/Video",
				"Term-end Portfolio",
			],
			[
				"Autodesk Maya",
				"Adobe Substance Painter",
				"Reality Capture",
				"Arnold",
				"Gen Ai tools for 3D Assets Creation & Animation",
				"Term-end Portfolio",
			],
			[
				"Autodesk Maya nCloth & X-Gen",
				"Houdini",
				"Silhouette",
				"3D Equalizer",
				"Nuke",
				"Term-end Portfolio",
				"LinkedIn",
				"Upwork",
			],
			[],
			[],
			[],
		],
		`https://drive.google.com/file/d/1XqcI6WJ-TWQPMWSu4u_RxzHBPPZAfnZy/view?usp=sharing`
	),
	new Course(
		"3179-AVGC-ADGAB",
		"AVGC - ADGAB - 3179",
		"Advanced Digital Graphics and Animation with Blender",
		"Mid",
		13,
		["3D Animation"],
		152860,
		144836,
		[
			["Adobe Photoshop CC", "Adobe Audition CC", "Adobe After Effects CC"],
			["Blender", "Term-end Portfolio", "LinkedIn", "Upwork"],
			[],
			[],
			[],
			[],
		],
		`https://drive.google.com/file/d/1L923wNfTzDdmtAjIibb4NOMdMYljKhn2/view?usp=sharing`
	),
	new Course(
		"3178-AVGC-ADGAM",
		"AVGC - ADGAM - 3178",
		"Advanced Digital Graphics and Animation with Maya",
		"Mid",
		14,
		["3D Animation"],
		161120,
		151326,
		[
			["Adobe Photoshop CC", "Adobe Audition CC", "Adobe After Effects CC"],
			["Autodesk Maya", "Arnold", "Term-end Portfolio", "LinkedIn", "Upwork"],
			[],
			[],
			[],
			[],
		],
		`https://drive.google.com/file/d/1_tqE1HoO4zr_gG-HugECmryBToPgRV6R/view?usp=sharing`
	),
	new Course(
		"3177-AVGC-APAVFX",
		"AVGC - Anivfx - 3177",
		"Advanced Program in Animation and VFX",
		"Long",
		23,
		["3D Animation", "VFX"],
		267432,
		239230,
		[
			[
				"Adobe Photoshop CC",
				"Adobe Premiere Pro",
				"Adobe Audition CC",
				"Adobe After Effects CC",
			],
			["Autodesk Maya", "Adobe Substance Painter", "Arnold"],
			[
				"Autodesk Maya nCloth & X-Gen",
				"Houdini",
				"Silhouette",
				"3D Equalizer",
				"Nuke",
				"Term-end Portfolio",
				"LinkedIn",
				"Upwork",
			],
			[],
			[],
			[],
		]
	),
	new Course(
		"3180-AVGC-APVFXCE",
		"AVGC - APVFXCE - 3180",
		"Advanced Program in VFX Compositing and Editing",
		"Mid",
		11,
		["VFX", "Video / Audio"],
		122180,
		116870,
		[
			[
				"Adobe Photoshop CC",
				"Adobe Premiere Pro",
				"Adobe Audition CC",
				"Adobe After Effects CC",
				"Nuke",
				"Silhouette",
				"DaVinci",
				"Term-end Portfolio",
				"LinkedIn",
				"Upwork",
			],
			[],
			[],
			[],
			[],
			[],
		],
		`https://drive.google.com/file/d/1qYoEoqt38vVMwadHyR5Ya7rHmtgegFJ0/view?usp=sharing`
	),
	new Course(
		"3181-AVGC-APVFXFM",
		"AVGC - APVFXFM - 3181",
		"Advanced Program in VFX Film Making",
		"Long",
		20,
		["VFX"],
		215040,
		195806,
		[
			[
				"Adobe Photoshop CC",
				"Storyboarder",
				"Adobe Premier Pro CC",
				"Adobe Audition CC",
				"Adobe After Effects CC",
			],
			["Autodesk Maya", "Adobe Substance Painter", "Arnold"],
			[
				"Silhouette",
				"3D Equalizer",
				"Nuke",
				"Term-end Portfolio",
				"LinkedIn",
				"Upwork",
			],
			[],
			[],
			[],
		]
	),
	new Course(
		"3176-AVGC-TRINITY",
		"AVGC - TRINITY - 3176",
		"Trinity 3D, Master in Realtime 3D, VFX and Game Development",
		"Long",
		36,
		["3D Animation", "VFX", "Game Design", "Game Development"],
		438060,
		356050,
		[
			[
				"Conceptual",
				"Storyboarder",
				"Adobe Illustrator CC",
				"Adobe Photoshop CC",
			],
			[
				"Adobe Premier Pro CC",
				"Adobe Audition CC",
				"Adobe Animate CC",
				"Adobe After Effects CC",
				"DaVinci",
				"Gen Ai tools for Text/Image/Video",
			],
			[
				"Conceptual",
				"Autodesk Maya",
				"Maxon Zbrush",
				"Adobe Substance Painter",
				"Arnold",
			],
			[
				"Autodesk Maya",
				"Gen Ai tools for 3D Assets",
				"Autodesk Maya nCloth & X-Gen",
				"Unreal Engine",
				"Meta Human",
			],
			[
				"Reality Capture",
				"Conceptual",
				"Houdini",
				"Silhouette",
				"3D Equalizer",
				"Nuke",
			],
			["Unreal Engine 5.0"],
		],
		`https://drive.google.com/file/d/1Snj7RCrYl34Og-v6mct8CKkhWPr_tquT/view?usp=sharing`
	),
	new Course(
		"3174-DCC-DCC",
		"DCC - DCC - 3174",
		"DCC-Digital Content Creation",
		"Mid",
		17,
		["Graphic Web Design and Development", "Motion Graphics Design"],
		196278,
		181764,
		[
			[
				"Adobe Photoshop CC",
				"Adobe Illustrator CC",
				"Adobe InDesign CC",
				"Canva/Adobe Express",
				"Adobe Dimensions",
				"Term-end Portfolio",
			],
			[
				"Adobe Premiere Pro CC",
				"Adobe Audition CC",
				"Adobe Animate CC",
				"Adobe After Effects CC",
				"DaVinci",
				"Gen Ai tools for text/image/video",
				"Term-end Portfolio",
			],
			[
				"Google Forms",
				"Microsoft Forms",
				"Pencil Project/Draw.io",
				"Figma",
				"Maze/UserTesting",
				"Visify",
				"Uizard",
				"Firefly",
				"VS Code",
				"WordPress",
				"XAMPP",
				"Term-end Portfolio",
				"LinkedIn",
				"Upwork",
			],
			[],
			[],
			[],
		],
		`https://drive.google.com/file/d/1JUEF1aqtpb7PaIGAhKcJRFCtyuLTu7BN/view?usp=sharing`
	),
	new Course(
		"3172-DCC-NGGD",
		"DCC - NGGWDD - 3172",
		"DCC-Next-Gen Graphic and Visual Design",
		"Short",
		8,
		["Graphics Design"],
		54148,
		52850,
		[
			[
				"Adobe Photoshop CC",
				"Adobe Illustrator CC",
				"Adobe InDesign CC",
				"Canva/Adobe Express",
				"Adobe Dimensions",
				"Term-end Portfolio",
			],
			[],
			[],
			[],
			[],
			[],
		],
		`https://drive.google.com/file/d/12UeZ5Sf1LCR81GhM-7p6gLXBQQu5YF33/view?usp=sharing`
	),
	new Course(
		"3172-DCC-NGGDWD",
		"DCC - NGGWDD - 3172",
		"DCC-Next-Gen Graphic Design and Web Development",
		"Mid",
		15,
		["Graphic Web Design and Development"],
		106540,
		100640,
		[
			[
				"Adobe Photoshop CC",
				"Adobe Illustrator CC",
				"Adobe InDesign CC",
				"Canva/Adobe Express",
				"Adobe Dimensions",
				"Pencil Project/Draw.io",
				"Term-end Portfolio",
			],
			[
				"Visify",
				"Uizard",
				"Figma",
				"Firefly",
				"HTML5 CSS3",
				"Bootstrap",
				"JavaScript",
				"WordPress",
				"XAMPP",
				"AdWords",
				"Analytics",
				"Yoast",
				"PHP and MySQL",
				"Term-end Portfolio",
				"LinkedIn",
				"Upwork",
			],
			[],
			[],
			[],
			[],
		],
		`https://drive.google.com/file/d/1KpxowVT8b1OYuzISk10KssuKxpcy25U2/view?usp=sharing`
	),
	new Course(
		"3172-DCC-NGWDD",
		"DCC - NGGWDD - 3172",
		"DCC-Next-Gen Web Design and Development",
		"Short",
		7,
		["Graphic Web Design and Development"],
		56980,
		55328,
		[
			[
				"Visify",
				"Uizard",
				"Figma",
				"Firefly",
				"HTML5 CSS3",
				"Bootstrap",
				"JavaScript",
				"WordPress",
				"XAMPP",
				"AdWords",
				"Analytics",
				"Yoast",
				"PHP and MySQL",
				"Term-end Portfolio",
				"LinkedIn",
				"Upwork",
			],
			[],
			[],
			[],
			[],
			[],
		],
		`https://drive.google.com/file/d/1XN1CGT-tzFKPf7MJ-uh50A4VqFXoJ-fU/view?usp=sharing`
	),
	new Course(
		"3173-DCC-NGVDMA",
		"DCC - NGVDMA - 3173",
		"DCC-Next-Gen Visual Design and Motion Graphics",
		"Mid",
		11,
		["Graphics Design", "Motion Graphics Design"],
		102882,
		98162,
		[
			[
				"Adobe Illustrator CC",
				"Adobe Photoshop CC",
				"Canva/Adobe Express",
				"Adobe Animate CC",
				"Adobe Premiere Pro CC",
				"Adobe Audition CC",
				"Adobe After Effects CC",
				"DaVinci",
				"Gen AI tools for Text/Image/Video",
				"Term-end Portfolio",
				"LinkedIn",
				"Upwork",
			],
			[],
			[],
			[],
			[],
			[],
		],
		`https://drive.google.com/file/d/1rTaJPnEhMccYm3VvaxGsBdOHtMa89ykC/view?usp=sharing`
	),
	new Course(
		"3175-GID-APGAD",
		"GID - MGADDARVR - 3175",
		"GID-Advanced Program in Game Art and Design",
		"Long",
		21,
		["Game Design"],
		227430,
		204656,
		[
			[
				"Adobe Illustrator CC",
				"Adobe Photoshop CC",
				"Figma",
				"Adobe Animate CC",
				"Gen AI tools for Text/Image/Video",
				"GDevelop.io",
			],
			[
				"Autodesk Maya",
				"Maxon Zbrush",
				"Adobe Substance Painter",
				"Unreal Engine (Designing)",
				"Gen AI tools for 3D Assets Creation & Animation",
			],
			[],
			[],
			[],
			[],
		]
	),
	new Course(
		"3175-GID-APGADD",
		"GID - MGADDARVR - 3175",
		"GID-Advanced Program in Game Art, Design and Development",
		"Long",
		28,
		["Game Design", "Game Development"],
		301770,
		260588,
		[
			[
				"Adobe Illustrator CC",
				"Adobe Photoshop CC",
				"Figma",
				"Adobe Animate CC",
				"Gen AI tools for Text/Image/Video",
				"GDevelop.io",
			],
			["Autodesk Maya", "Maxon Zbrush", "Adobe Substance Painter"],
			[
				"Unreal Engine",
				"Gen AI tools for 3D Assets Creation & Animation",
				"Term-end Portfolio",
			],
			[],
			[],
			[],
		]
	),
	new Course(
		"3175-GID-APGADS",
		"GID - MGADDARVR - 3175",
		"GID-Advanced Program in Game Art and Design with Specialization",
		"Long",
		27,
		["Game Design"],
		286784,
		251266,
		[
			[
				"Adobe Illustrator CC",
				"Adobe Photoshop CC",
				"Figma",
				"Adobe Animate CC",
				"Gen AI tools for Text/Image/Video",
				"GDevelop.io",
			],
			[
				"Autodesk Maya",
				"Maxon Zbrush",
				"Adobe Substance Painter",
				"Unreal Engine (Designing)",
				"Gen AI tools for 3D Assets Creation & Animation",
			],
			["Specialization in Game Art"],
			[],
			[],
			[],
		]
	),
	new Course(
		"3175-GID-APID",
		"GID - MGADDARVR - 3175",
		"GID-Advanced Program in Immersive Design",
		"Long",
		26,
		["Game Design"],
		274512,
		241826,
		[
			[
				"Adobe Illustrator CC",
				"Adobe Photoshop CC",
				"Figma",
				"Adobe Animate CC",
				"Gen AI tools for Text/Image/Video",
				"GDevelop.io",
			],
			["Autodesk Maya", "Maxon Zbrush", "Adobe Substance Painter"],
			[
				"Unity",
				"Unreal Engine",
				"Gen AI tools for 3D Assets Creation & Animation",
				"Term-end Portfolio",
			],
			[],
			[],
			[],
		]
	),
	new Course(
		"3175-GID-MGADDARVR",
		"GID - MGADDARVR - 3175",
		"GID-Master in Game Art, Design and Dev with ARVRXR",
		"Long",
		39,
		["Game Design", "Game Development"],
		409504,
		336462,
		[
			[
				"Adobe Illustrator CC",
				"Adobe Photoshop CC",
				"Figma",
				"Adobe Animate CC",
				"Gen AI tools for Text/Image/Video",
				"GDevelop.io",
			],
			[
				"Autodesk Maya",
				"Maxon Zbrush",
				"Adobe Substance Painter",
				"Unreal Engine",
				"Gen AI tools for 3D Assets Creation & Animation",
				"Term-end Portfolio",
			],
			[
				"Blender",
				"Substance Designer",
				"Adobe Stager",
				"Reality Capture",
				"Term-end Portfolio",
			],
			["Unreal Engine"],
			[
				"Spark AR",
				"Unreal Engine",
				"Unity3D",
				"Term-end Portfolio",
				"LinkedIn",
				"Upwork",
			],
			[],
		],
		`https://drive.google.com/file/d/1swP898ag1tkty3iG9KEwPHf0sJOSpjfo/view?usp=sharing`
	),
	new Course(
		"OV-3095-APUIUX",
		"OV-3095-APUIUX",
		"Advanced Program in UI UX Design",
		"Mid",
		7,
		["UI/UX"],
		85196,
		83308,
		[
			[
				"Adobe Photoshop CC",
				"Adobe Illustrator CC",
				"Google Form",
				"Microsoft Forms",
				"Pencil Project/Draw.io",
				"Figma",
				"Maze/User Testing",
				"Visify",
				"Uizard",
				"Firefly",
				"VS Code",
				"WordPress",
				"XAMPP",
				"Project",
				"Behance",
				"Dribbble",
			],
			[],
			[],
			[],
			[],
			[],
		],
		`https://drive.google.com/file/d/1m8oC5HVdaIcKn2iUuYNA5X-vB6I1OsjB/view?usp=sharing`
	),
	new Course(
		"660-MGAI",
		"STCs",
		"Master in Gen AI",
		"Short",
		2,
		["AI"],
		16992,
		16992,
		[
			[
				"Concept + ChatGPT Plus",
				"Deep Seek",
				"Leonardo Ai + Midjourney + Adobe Photoshop",
				"+ Leonardo Ai",
				"Canva Ai / Adobe Express Ai Tools",
				"Sora + Runway ML + Adobe After Effects + Premiere",
				"Eleven Labs + Suno Ai + Adobe Audition",
				"Meshy Ai + Zbrush",
			],
			[],
			[],
			[],
			[],
			[],
		],
		`https://drive.google.com/file/d/1old1RbsUlvxUIdXl6yUb0aUhLTjNdlKj/view?usp=sharing`
	),
	new Course(
		"661-MH",
		"STCs",
		"Master in Houdini",
		"Short",
		2,
		["VFX"],
		21358,
		21358,
		[["Houdini"], [], [], [], [], []]
	),
	new Course(
		"662-M2DA",
		"STCs",
		"Master in 2D Animation",
		"Short",
		9,
		["2D Animation"],
		89208,
		85786,
		[
			[
				"Storyboarder",
				"Adobe Photoshop CC",
				"Adobe Animate CC",
				"Adobe Premiere Pro CC",
				"Adobe Audition CC",
			],
			[],
			[],
			[],
			[],
			[],
		]
	),
	new Course(
		"663-MZB",
		"STCs",
		"Master in Zbrush",
		"Short",
		2,
		["3D Animation"],
		17818,
		17818,
		[["Z brush"], [], [], [], [], []]
	),
	new Course(
		"664-MBL",
		"STCs",
		"Master in Blender",
		"Short",
		7,
		["3D Animation"],
		70210,
		68322,
		[["Blender"], [], [], [], [], []]
	),
	new Course(
		"666-MPH",
		"STCs",
		"Master in Photoshop",
		"Short",
		2,
		["Graphics Design"],
		21358,
		21358,
		[["Photoshop"], [], [], [], [], []]
	),
	new Course(
		"667-MIL",
		"STCs",
		"Master in Illustrator",
		"Short",
		2,
		["Graphics Design"],
		10856,
		10856,
		[["Illustrator"], [], [], [], [], []]
	),
	new Course(
		"668-MUC",
		"STCs",
		"Master in Unreal Cinematics",
		"Short",
		3,
		["Game Design"],
		32096,
		31742,
		[["Unreal Engine"], [], [], [], [], []]
	),
	new Course(
		"669-MC4D",
		"STCs",
		"Master in Cinema 4D",
		"Short",
		3,
		["3D Animation", "Motion Graphics Design"],
		32096,
		31742,
		[["Cinema 4D"], [], [], [], [], []]
	),
	new Course(
		"670-MAE",
		"STCs",
		"Master in After Effects",
		"Short",
		2,
		["Motion Graphics Design"],
		17110,
		17110,
		[["After Effects"], [], [], [], [], []]
	),
	new Course(
		"671-MID",
		"STCs",
		"Master in InDesign",
		"Short",
		2,
		["Graphics Design"],
		11682,
		11682,
		[["InDesign"], [], [], [], [], []]
	),
	new Course(
		"672-MSP",
		"STCs",
		"Master in Substance Painter",
		"Short",
		2,
		["3D Animation"],
		15458,
		15458,
		[["Substance Painter"], [], [], [], [], []]
	),
	new Course(
		"673-MAVE",
		"STCs",
		"Master in Audio Video Editing",
		"Short",
		3,
		["Video / Audio"],
		25606,
		25606,
		[["Adobe Premier Pro"], ["Adobe Audition"], [], [], [], []]
	),
	new Course(
		"674-M3DM",
		"STCs",
		"Master in 3ds Max",
		"Short",
		5,
		["3D Animation"],
		51330,
		50504,
		[["3Ds Max"], [], [], [], [], []]
	),
	new Course(
		"675-MP",
		"STCs",
		"Master in Photography",
		"Short",
		2,
		["Graphics Design"],
		17110,
		17110,
		[["Photography"], [], [], [], [], []]
	),
	new Course(
		"676-MUE",
		"STCs",
		"Master in Unreal Engine",
		"Short",
		7,
		["Game Design"],
		76700,
		75048,
		[["Unreal Engine"], [], [], [], [], []]
	),
	new Course(
		"677-MM",
		"STCs",
		"Master in Maya",
		"Short",
		9,
		["3D Animation"],
		66906,
		64310,
		[["Maya"], [], [], [], [], []]
	),
	new Course(
		"678-MNS",
		"STCs",
		"Master in Nuke and Silhouette",
		"Short",
		4,
		["VFX"],
		45548,
		44958,
		[["Nuke and Silhouette"], [], [], [], [], []]
	),

	new Course(
		"OV-587-BE",
		"STCs",
		"Broadcast Editing",
		"Short",
		5,
		["3D Animation", "Motion Graphics Design", "Video / Audio"],
		49442,
		48734,
		[[], [], [], [], [], []]
	),
	new Course(
		"OV-3108 Bvoc FM",
		"B. Voc (VFA)",
		"B. Voc (VFA)",
		"Long",
		36,
		["VFX", "3D Animation"],
		455000,
		undefined,
		[
			["Adobe Illustrator CC", "Adobe Photoshop CC", "Adobe Express", "Canva"],
			[
				"Adobe Audition CC",
				"Adobe Premiere Pro CC",
				"Adobe After Effects",
				"Adobe Animate CC",
			],
			["Autodesk 3ds Max with Vray"],
			["Autodesk Maya", "Zbrush", "Substance Painter"],
			["Autodesk Maya (Rigging and Animation)", "X-Gen", "Cloth"],
			[
				"Foundry Nuke,Unreal Engine",
				"Metahuman",
				"Silhouette",
				"Mocha",
				"DaVinci Resolve",
				"Portfolio",
			],
		],
		`https://drive.google.com/file/d/1ragQ6MHDmbVkWA29T6rKhbgLPUlbYDuO/view?usp=sharing`,
		true
	),
	new Course(
		"665-DAID",
		"STCs",
		"Digital Architecture and Interior Design",
		"Short",
		8,
		["Interior/ Exterior"],
		75048,
		72452,
		[
			["Adobe Photoshop CC", "3ds Max", "Vray", "Twinmotion"],
			[],
			[],
			[],
			[],
			[],
		]
	),
];
